name: Deploy to Synology NAS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/synology_nas
        chmod 600 ~/.ssh/synology_nas
        ssh-keyscan -H ${{ secrets.NAS_HOST }} >> ~/.ssh/known_hosts

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.0

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan \
          -var="nas_host=${{ secrets.NAS_HOST }}" \
          -var="nas_username=${{ secrets.SSH_USER }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: |
        cd terraform
        terraform apply \
          -var="nas_host=${{ secrets.NAS_HOST }}" \
          -var="nas_username=${{ secrets.SSH_USER }}" \
          -auto-approve

    - name: Clean up
      run: |
        rm -f ~/.ssh/synology_nas